### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by notpushkin** [eqlion/rn-wage#1]
If you're not planning on closing the source code afterwards, adding a proper open source license would be great! If you need help choosing, [GPL-3.0] or [ISC] might be suitable depending on your personal preferences.

[GPL-3.0]: https://www.gnu.org/licenses/gpl-3.0.en.html
[ISC]: https://opensource.org/licenses/ISC

**Comment by eqlion** [comment]
Thank you for a reminder, I've just added GPL-3.0!
